---
- name: Installing packages for python env
  become: true
  ansible.builtin.apt:
    name:
      - python3-pip
    update_cache: true

- name: Install ansible-dev-tools
  become: true
  ansible.builtin.pip:
    name:
      - ansible-dev-tools
