---
- name: installing packages for python env
  become: yes
  apt:
    name:
      - python3-pip
    update_cache: yes

- name: install ansible-dev-tools
  become: yes
  pip: 
    name: 
      - ansible-dev-tools