---
- name: Install Developer tools
  ansible.builtin.apt:
    name:
      - neovim
    state: present
    update_cache: true

- name: Install Codium (VSCode)
  community.general.snap:
    name:
      - codium
    classic: true
    state: present

- name: Add Github official GPG key
  ansible.builtin.apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    state: present

- name: Add Github APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present

- name: Install Github Desktop
  ansible.builtin.apt:
    name:
      - brave
    state: present
    update_cache: true
