---
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt package index after adding Docker repo
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker CE
  ansible.builtin.apt:
    name: docker-ce
    state: present
  notify: Restart Docker

- name: Add current user to Docker group (to run docker without sudo)
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
