---
- name: Example Ansible playbook
  hosts: ubuntu
  become: true
  gather_facts: true

  tasks:
    - name: Installing packages for python env
      become: true
      ansible.builtin.apt:
        name:
          - python3-pip
        update_cache: false
  #    when: ansible_facts['os_family'] == 'RHEL'

    - name: Install ansible-dev-tools
      become: false
      ansible.builtin.pip:
        name:
          - ansible-dev-tools

    - name: Debug
      ansible.builtin.debug:
        var: ansible_facts['os_family']
